### PR TITLE
Enabled tests and refactored `ETException`

### PR DESCRIPTION
**Pull request by johnzeringue**
A continuation of #3 that correctly specifies `CIRDLES:dev` as the pull request target (instead of `CIRDLES:master`). Please reference the old thread for past discussion.

### CODE REVIEW

**Comment by johnzeringue** [comment]
I've gone through, made a few final changes, and squashed my commits. As far I can tell, this is production ready.

@bowring, if you're happy with the current state of the pull request, I'd say to merge it.

**Comment by johnzeringue** [comment]
@bowring, I've updated my pull request to be compatible with the changes in #5.

**Comment by bowring** [comment]
Looking good. The EARTHTIME message pane still appears behind labdata
window, however.  If you add setAlwaysOnTop(true); to the end of
configureThis() in ETWarningDialog, it should do the trick.



On Mon, Mar 23, 2015 at 9:33 AM, John Zeringue <notifications@github.com>
wrote:

> @bowring <https://github.com/bowring>, I've updated my pull request to be
> compatible with the changes in #5
> <https://github.com/CIRDLES/ET_Redux/pull/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/ET_Redux/pull/4#issuecomment-84998497>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org <http://www.CIRDLES.org%20>

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by johnzeringue** [comment]
I made the change. Please confirm that it works.

**Comment by bowring** [comment]
Great job - thanks!

**Pull request merged**
